---
# LoadBalancer Service used to access Python Web deployment
# 
# Deploy as follows:
# kubectl create -f webapp-services.yml
# 
# Verify as follows:
# kubectl get services -n p20-webapps
# 
# kubectl describe service webapp-loadbalancer -n p20-webapps
#
# This is how to delete this service
# kubectl delete service webapp-loadbalancer -n p20-webapps
#
apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer
  namespace: p20-webapps
  labels:
    k8s-app: webapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: nginx-webapp
