---
# This is how to create the resource
# kubectl create -f webapp-namespace.yml
# This is how to verify if the namespace as created:
# kubectl get namespaces
# 
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appData.namespace }}
  labels:
    name: {{ .Values.appData.namespace }}