# Default values for app-languages.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appData:
  label: "nginx-webapp"
  imageName: "p20izzyacr.azurecr.io/nginxserver"
  imageVersion: "latest"
   
